FROM node:20

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@9.12.3 --activate

COPY package.json ./
RUN pnpm install --frozen-lockfile=false --prod

COPY server ./server
COPY public ./public
COPY db ./db

ENV NODE_ENV=production
ENV PORT=5174

EXPOSE 5174

CMD ["node","server/index.js"]
