FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY server ./server
COPY public ./public
COPY db ./db

ENV NODE_ENV=production
ENV PORT=5174

EXPOSE 5174

CMD ["node","server/index.js"]
